### ISSUE TITLE
Could not find declared class ceph::conf 

### ISSUE THREAD

**Issue by kenny-opennix** [enovance/puppet-ceph#80]
Hello, i am install you plugin, and use your example file,but get error

**Comment by Quentin-M** [comment]
Hello sir.

I faced his issue yesterday and it appears that I also had an error about an unreadable character in US-ASCII in this class, sometimes (Puppet uses a cache system...).

I fixed it by adding the following line in `/usr/share/puppet/ext/rack/config.ru` on the puppet master node: 
```
Encoding.default_external = Encoding::UTF_8
```

Do not add this line at the end of the file but before the final call. You may need to restart puppetmaster.

Have a nice day.

**Comment by kenny-opennix** [comment]
thanks for the reply, but now is such a mistake. Apparently I was wrong in the manifest

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter cluster_network on Class[Ceph::Conf] at /etc/puppet/manifests/site.pp:24 on node
Warning: Not using cache on failed catalog

**Comment by Quentin-M** [comment]
Try by replacing `${::network_eth2}/24`maybe ?

**Comment by kenny-opennix** [comment]
no it did not help.
I tried to set the network 1.2.3.4/24 and received the same error.

**Comment by kenny-opennix** [comment]
i am fix problem, but on osd no keyring file. How it fix?

**Comment by kenny-opennix** [comment]
sorry this error it was my fault
